<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC2hw8nu\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC2hw8nu/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerC2hw8nu.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerC2hw8nu\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerC2hw8nu\App_KernelProdContainer([
    'container.build_hash' => 'C2hw8nu',
    'container.build_id' => 'ed7d9127',
    'container.build_time' => 1624636611,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC2hw8nu');
