<?php

namespace Container7RDnvQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cuv0NPyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cuv0NPy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cuv0NPy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'punishment' => ['privates', '.errored..service_locator.cuv0NPy.App\\Entity\\Punishment', NULL, 'Cannot autowire service ".service_locator.cuv0NPy": it references class "App\\Entity\\Punishment" but no such service exists.'],
        ], [
            'punishment' => 'App\\Entity\\Punishment',
        ]);
    }
}
