<?php

namespace Container7RDnvQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbscenceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.P8gYjlh.App\Entity\Abscence' shared service.
     *
     * @return \App\Entity\Abscence
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.P8gYjlh": it references class "App\\Entity\\Abscence" but no such service exists.');
    }
}
