<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYFvYqZt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYFvYqZt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYFvYqZt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYFvYqZt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYFvYqZt\App_KernelDevDebugContainer([
    'container.build_hash' => 'YFvYqZt',
    'container.build_id' => 'fdf4bc35',
    'container.build_time' => 1624621958,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYFvYqZt');
