<?php

namespace ContainerC2hw8nu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NHrpuLYService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.NHrpuLY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NHrpuLY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'student' => ['privates', '.errored..service_locator.NHrpuLY.App\\Entity\\Student', NULL, 'Cannot autowire service ".service_locator.NHrpuLY": it references class "App\\Entity\\Student" but no such service exists.'],
        ], [
            'student' => 'App\\Entity\\Student',
        ]);
    }
}
