<?php

namespace ContainerC2hw8nu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbscenceRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AbscenceRepository' shared autowired service.
     *
     * @return \App\Repository\AbscenceRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AbscenceRepository'] = new \App\Repository\AbscenceRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
