<?php

namespace ContainerC2hw8nu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\GroupType' shared autowired service.
     *
     * @return \App\Form\GroupType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\GroupType'] = new \App\Form\GroupType();
    }
}
