<?php

namespace ContainerC2hw8nu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\GroupRepository' shared autowired service.
     *
     * @return \App\Repository\GroupRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\GroupRepository'] = new \App\Repository\GroupRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
