<?php

namespace ContainerC2hw8nu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\GroupController' shared autowired service.
     *
     * @return \App\Controller\GroupController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\GroupController'] = $instance = new \App\Controller\GroupController(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\GroupController', $container));

        return $instance;
    }
}
