<?php

namespace ContainerC2hw8nu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPunishmentRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PunishmentRepository' shared autowired service.
     *
     * @return \App\Repository\PunishmentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PunishmentRepository'] = new \App\Repository\PunishmentRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
